//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLClient_Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anh
    {
        public int idAnh { get; set; }
        public string link { get; set; }
        public Nullable<int> idSp { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
