//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLClient_Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DonHang
    {
        public int idDon { get; set; }
        public int idSp { get; set; }
        public Nullable<double> giaBan { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<double> thanhTien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
