//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLClient_Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CT_DonHang = new HashSet<CT_DonHang>();
        }
    
        public int idDon { get; set; }
        public Nullable<System.DateTime> ngayDat { get; set; }
        public string diaChiGiao { get; set; }
        public string moTa { get; set; }
        public Nullable<double> tongTien { get; set; }
        public Nullable<int> idKhach { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> trangThai { get; set; }
        public string donViGiao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DonHang> CT_DonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
