//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLClient_Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int IdLienHe { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> idKhach { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
