//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLClient_Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.Anhs = new HashSet<Anh>();
            this.CT_DonHang = new HashSet<CT_DonHang>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public int idSp { get; set; }
        public string ten { get; set; }
        public string moTa { get; set; }
        public string chiTiet { get; set; }
        public Nullable<double> gia { get; set; }
        public Nullable<double> giaKm { get; set; }
        public Nullable<int> trangThai { get; set; }
        public Nullable<int> idLoai { get; set; }
        public Nullable<int> idThuongHieu { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string trangThaiMieuTa { get; set; }
        public string anhDaiDien { get; set; }
        public string MieuTaSanPhamNoiBat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anh> Anhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DonHang> CT_DonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual LoaiSp LoaiSp { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
