//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLClient_Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int idTin { get; set; }
        public string tieuDe { get; set; }
        public string anh { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<int> idUser { get; set; }
    }
}
