//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLClient_Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUser { get; set; }
        public string hoTen { get; set; }
        public string tenDangNhap { get; set; }
        public string matKhau { get; set; }
        public Nullable<int> quyen { get; set; }
        public Nullable<bool> trangThai { get; set; }
    }
}
